#!/bin/sh
# $OpenBSD: Xsetup_0,v 1.8 2020/07/04 13:32:50 matthieu Exp $
xrandr --output default --dpi 96
xsetroot -solid black

(
while true; do
	xmessage -geometry +540-32 \
		-buttons "[ Sleep ]":20,"[ Restart ]":21,"[ Shutdown ]":22 ""
	ACTION=$?
	echo "Xmessage said: $ACTION"
	if   [ $ACTION -eq 20 ]; then /usr/sbin/zzz;
	elif [ $ACTION -eq 21 ]; then
		xsetroot -cursor_name watch
		/sbin/shutdown -r now
	elif [ $ACTION -eq 22 ]; then
		xsetroot -cursor_name watch
		/sbin/shutdown -p now
	else echo "Something bad happened to Xmessage.";
	fi
	# stop looping if xclock died (hopefully killed by GiveConsole)
	if [ -z "$(pgrep -U root xclock)" ]; then break; fi
done
) &

OS_NAME=$(uname -sr)

xclock -digital -geometry -0+0 \
	  -strftime "$OS_NAME | %a. %d %b. %Y  %H:%M " & 
